# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b86ca123797e09ac381110ce20a9c8f9cce8a001d1a9d503c56b846143f6730e3baa4b16ead35776c8c96b1e28296aaaf2e8aeab6b3e69306cf977530695e45

test:
  secret_key_base: 5fe75ab720627b742829432801ad243febea5f298004b250450548920d20902232a38985f164d01a1eeb2e75b4bf988c37873c2217ee09ae4ce8dbbc63b5914b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
